# SRun Auto Login 配置文件
USERNAME="18686153955"
PASSWORD="18686153955"
GATEWAY="gw.imust.edu.cn"
GATEWAY_IP="10.16.42.48"
AC_ID="6"
SSIDS="imust,THUNDER"
MAX_RETRY=3
CHECK_INTERVAL=5
SUCCESS_INTERVAL=30
